//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workforce.Logic.Felice.Tests.WorkforceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkforceServiceReference.IFeliceService")]
    public interface IFeliceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAssociates", ReplyAction="http://tempuri.org/IFeliceService/GetAssociatesResponse")]
        Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[] GetAssociates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAssociates", ReplyAction="http://tempuri.org/IFeliceService/GetAssociatesResponse")]
        System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[]> GetAssociatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAddress", ReplyAction="http://tempuri.org/IFeliceService/GetAddressResponse")]
        Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao[] GetAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAddress", ReplyAction="http://tempuri.org/IFeliceService/GetAddressResponse")]
        System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao[]> GetAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/GetAssociateAddressResponse")]
        Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao[] GetAssociateAddress();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/GetAssociateAddressResponse")]
        System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao[]> GetAssociateAddressAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetBatches", ReplyAction="http://tempuri.org/IFeliceService/GetBatchesResponse")]
        Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao[] GetBatches();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetBatches", ReplyAction="http://tempuri.org/IFeliceService/GetBatchesResponse")]
        System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao[]> GetBatchesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetInstructor", ReplyAction="http://tempuri.org/IFeliceService/GetInstructorResponse")]
        Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao[] GetInstructor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetInstructor", ReplyAction="http://tempuri.org/IFeliceService/GetInstructorResponse")]
        System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao[]> GetInstructorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetGender", ReplyAction="http://tempuri.org/IFeliceService/GetGenderResponse")]
        Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao[] GetGender();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetGender", ReplyAction="http://tempuri.org/IFeliceService/GetGenderResponse")]
        System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao[]> GetGenderAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertAssociate", ReplyAction="http://tempuri.org/IFeliceService/InsertAssociateResponse")]
        bool InsertAssociate(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao newassociate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertAssociate", ReplyAction="http://tempuri.org/IFeliceService/InsertAssociateResponse")]
        System.Threading.Tasks.Task<bool> InsertAssociateAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao newassociate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertAddress", ReplyAction="http://tempuri.org/IFeliceService/InsertAddressResponse")]
        bool InsertAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao newaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertAddress", ReplyAction="http://tempuri.org/IFeliceService/InsertAddressResponse")]
        System.Threading.Tasks.Task<bool> InsertAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao newaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/InsertAssociateAddressResponse")]
        bool InsertAssociateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao newassocaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/InsertAssociateAddressResponse")]
        System.Threading.Tasks.Task<bool> InsertAssociateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao newassocaddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertBatch", ReplyAction="http://tempuri.org/IFeliceService/InsertBatchResponse")]
        bool InsertBatch(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao newbatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertBatch", ReplyAction="http://tempuri.org/IFeliceService/InsertBatchResponse")]
        System.Threading.Tasks.Task<bool> InsertBatchAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao newbatch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertGender", ReplyAction="http://tempuri.org/IFeliceService/InsertGenderResponse")]
        bool InsertGender(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao newgender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertGender", ReplyAction="http://tempuri.org/IFeliceService/InsertGenderResponse")]
        System.Threading.Tasks.Task<bool> InsertGenderAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao newgender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertInstructor", ReplyAction="http://tempuri.org/IFeliceService/InsertInstructorResponse")]
        bool InsertInstructor(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao newinstructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/InsertInstructor", ReplyAction="http://tempuri.org/IFeliceService/InsertInstructorResponse")]
        System.Threading.Tasks.Task<bool> InsertInstructorAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao newinstructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateAssociate", ReplyAction="http://tempuri.org/IFeliceService/UpdateAssociateResponse")]
        bool UpdateAssociate(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateAssociate", ReplyAction="http://tempuri.org/IFeliceService/UpdateAssociateResponse")]
        System.Threading.Tasks.Task<bool> UpdateAssociateAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateAddress", ReplyAction="http://tempuri.org/IFeliceService/UpdateAddressResponse")]
        bool UpdateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateAddress", ReplyAction="http://tempuri.org/IFeliceService/UpdateAddressResponse")]
        System.Threading.Tasks.Task<bool> UpdateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/UpdateAssociateAddressResponse")]
        bool UpdateAssociateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/UpdateAssociateAddressResponse")]
        System.Threading.Tasks.Task<bool> UpdateAssociateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateBatch", ReplyAction="http://tempuri.org/IFeliceService/UpdateBatchResponse")]
        bool UpdateBatch(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateBatch", ReplyAction="http://tempuri.org/IFeliceService/UpdateBatchResponse")]
        System.Threading.Tasks.Task<bool> UpdateBatchAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateGender", ReplyAction="http://tempuri.org/IFeliceService/UpdateGenderResponse")]
        bool UpdateGender(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateGender", ReplyAction="http://tempuri.org/IFeliceService/UpdateGenderResponse")]
        System.Threading.Tasks.Task<bool> UpdateGenderAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateInstructor", ReplyAction="http://tempuri.org/IFeliceService/UpdateInstructorResponse")]
        bool UpdateInstructor(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/UpdateInstructor", ReplyAction="http://tempuri.org/IFeliceService/UpdateInstructorResponse")]
        System.Threading.Tasks.Task<bool> UpdateInstructorAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteAssociate", ReplyAction="http://tempuri.org/IFeliceService/DeleteAssociateResponse")]
        bool DeleteAssociate(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteAssociate", ReplyAction="http://tempuri.org/IFeliceService/DeleteAssociateResponse")]
        System.Threading.Tasks.Task<bool> DeleteAssociateAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteAddress", ReplyAction="http://tempuri.org/IFeliceService/DeleteAddressResponse")]
        bool DeleteAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteAddress", ReplyAction="http://tempuri.org/IFeliceService/DeleteAddressResponse")]
        System.Threading.Tasks.Task<bool> DeleteAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/DeleteAssociateAddressResponse")]
        bool DeleteAssociateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteAssociateAddress", ReplyAction="http://tempuri.org/IFeliceService/DeleteAssociateAddressResponse")]
        System.Threading.Tasks.Task<bool> DeleteAssociateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteBatch", ReplyAction="http://tempuri.org/IFeliceService/DeleteBatchResponse")]
        bool DeleteBatch(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteBatch", ReplyAction="http://tempuri.org/IFeliceService/DeleteBatchResponse")]
        System.Threading.Tasks.Task<bool> DeleteBatchAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteGender", ReplyAction="http://tempuri.org/IFeliceService/DeleteGenderResponse")]
        bool DeleteGender(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteGender", ReplyAction="http://tempuri.org/IFeliceService/DeleteGenderResponse")]
        System.Threading.Tasks.Task<bool> DeleteGenderAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteInstructor", ReplyAction="http://tempuri.org/IFeliceService/DeleteInstructorResponse")]
        bool DeleteInstructor(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/DeleteInstructor", ReplyAction="http://tempuri.org/IFeliceService/DeleteInstructorResponse")]
        System.Threading.Tasks.Task<bool> DeleteInstructorAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeliceServiceChannel : Workforce.Logic.Felice.Tests.WorkforceServiceReference.IFeliceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeliceServiceClient : System.ServiceModel.ClientBase<Workforce.Logic.Felice.Tests.WorkforceServiceReference.IFeliceService>, Workforce.Logic.Felice.Tests.WorkforceServiceReference.IFeliceService {
        
        public FeliceServiceClient() {
        }
        
        public FeliceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeliceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeliceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeliceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[] GetAssociates() {
            return base.Channel.GetAssociates();
        }
        
        public System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[]> GetAssociatesAsync() {
            return base.Channel.GetAssociatesAsync();
        }
        
        public Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao[] GetAddress() {
            return base.Channel.GetAddress();
        }
        
        public System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao[]> GetAddressAsync() {
            return base.Channel.GetAddressAsync();
        }
        
        public Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao[] GetAssociateAddress() {
            return base.Channel.GetAssociateAddress();
        }
        
        public System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao[]> GetAssociateAddressAsync() {
            return base.Channel.GetAssociateAddressAsync();
        }
        
        public Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao[] GetBatches() {
            return base.Channel.GetBatches();
        }
        
        public System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao[]> GetBatchesAsync() {
            return base.Channel.GetBatchesAsync();
        }
        
        public Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao[] GetInstructor() {
            return base.Channel.GetInstructor();
        }
        
        public System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao[]> GetInstructorAsync() {
            return base.Channel.GetInstructorAsync();
        }
        
        public Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao[] GetGender() {
            return base.Channel.GetGender();
        }
        
        public System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao[]> GetGenderAsync() {
            return base.Channel.GetGenderAsync();
        }
        
        public bool InsertAssociate(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao newassociate) {
            return base.Channel.InsertAssociate(newassociate);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAssociateAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao newassociate) {
            return base.Channel.InsertAssociateAsync(newassociate);
        }
        
        public bool InsertAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao newaddress) {
            return base.Channel.InsertAddress(newaddress);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao newaddress) {
            return base.Channel.InsertAddressAsync(newaddress);
        }
        
        public bool InsertAssociateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao newassocaddress) {
            return base.Channel.InsertAssociateAddress(newassocaddress);
        }
        
        public System.Threading.Tasks.Task<bool> InsertAssociateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao newassocaddress) {
            return base.Channel.InsertAssociateAddressAsync(newassocaddress);
        }
        
        public bool InsertBatch(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao newbatch) {
            return base.Channel.InsertBatch(newbatch);
        }
        
        public System.Threading.Tasks.Task<bool> InsertBatchAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao newbatch) {
            return base.Channel.InsertBatchAsync(newbatch);
        }
        
        public bool InsertGender(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao newgender) {
            return base.Channel.InsertGender(newgender);
        }
        
        public System.Threading.Tasks.Task<bool> InsertGenderAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao newgender) {
            return base.Channel.InsertGenderAsync(newgender);
        }
        
        public bool InsertInstructor(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao newinstructor) {
            return base.Channel.InsertInstructor(newinstructor);
        }
        
        public System.Threading.Tasks.Task<bool> InsertInstructorAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao newinstructor) {
            return base.Channel.InsertInstructorAsync(newinstructor);
        }
        
        public bool UpdateAssociate(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc) {
            return base.Channel.UpdateAssociate(assoc);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAssociateAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc) {
            return base.Channel.UpdateAssociateAsync(assoc);
        }
        
        public bool UpdateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address) {
            return base.Channel.UpdateAddress(address);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address) {
            return base.Channel.UpdateAddressAsync(address);
        }
        
        public bool UpdateAssociateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd) {
            return base.Channel.UpdateAssociateAddress(assocadd);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateAssociateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd) {
            return base.Channel.UpdateAssociateAddressAsync(assocadd);
        }
        
        public bool UpdateBatch(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch) {
            return base.Channel.UpdateBatch(batch);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateBatchAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch) {
            return base.Channel.UpdateBatchAsync(batch);
        }
        
        public bool UpdateGender(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender) {
            return base.Channel.UpdateGender(gender);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateGenderAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender) {
            return base.Channel.UpdateGenderAsync(gender);
        }
        
        public bool UpdateInstructor(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor) {
            return base.Channel.UpdateInstructor(instructor);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInstructorAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor) {
            return base.Channel.UpdateInstructorAsync(instructor);
        }
        
        public bool DeleteAssociate(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc) {
            return base.Channel.DeleteAssociate(assoc);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAssociateAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao assoc) {
            return base.Channel.DeleteAssociateAsync(assoc);
        }
        
        public bool DeleteAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address) {
            return base.Channel.DeleteAddress(address);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AddressDao address) {
            return base.Channel.DeleteAddressAsync(address);
        }
        
        public bool DeleteAssociateAddress(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd) {
            return base.Channel.DeleteAssociateAddress(assocadd);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAssociateAddressAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateAddressDao assocadd) {
            return base.Channel.DeleteAssociateAddressAsync(assocadd);
        }
        
        public bool DeleteBatch(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch) {
            return base.Channel.DeleteBatch(batch);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteBatchAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.BatchDao batch) {
            return base.Channel.DeleteBatchAsync(batch);
        }
        
        public bool DeleteGender(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender) {
            return base.Channel.DeleteGender(gender);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteGenderAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.GenderDao gender) {
            return base.Channel.DeleteGenderAsync(gender);
        }
        
        public bool DeleteInstructor(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor) {
            return base.Channel.DeleteInstructor(instructor);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteInstructorAsync(Workforce.Logic.Felice.Domain.WorkforceServiceReference.InstructorDao instructor) {
            return base.Channel.DeleteInstructorAsync(instructor);
        }
    }
}
