//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workforce.Logic.Felice.Tests.WorkforceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkforceServiceReference.IFeliceService")]
    public interface IFeliceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAssociates", ReplyAction="http://tempuri.org/IFeliceService/GetAssociatesResponse")]
        Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[] GetAssociates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeliceService/GetAssociates", ReplyAction="http://tempuri.org/IFeliceService/GetAssociatesResponse")]
        System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[]> GetAssociatesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeliceServiceChannel : Workforce.Logic.Felice.Tests.WorkforceServiceReference.IFeliceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeliceServiceClient : System.ServiceModel.ClientBase<Workforce.Logic.Felice.Tests.WorkforceServiceReference.IFeliceService>, Workforce.Logic.Felice.Tests.WorkforceServiceReference.IFeliceService {
        
        public FeliceServiceClient() {
        }
        
        public FeliceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeliceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeliceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeliceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[] GetAssociates() {
            return base.Channel.GetAssociates();
        }
        
        public System.Threading.Tasks.Task<Workforce.Logic.Felice.Domain.WorkforceServiceReference.AssociateDao[]> GetAssociatesAsync() {
            return base.Channel.GetAssociatesAsync();
        }
    }
}
